# permissions for end users to view opensearchuserrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchuserrolebinding-viewer-role
rules:
- apiGroups:
  - opensearch.org
  resources:
  - opensearchuserrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.org
  resources:
  - opensearchuserrolebindings/status
  verbs:
  - get
