# permissions for end users to edit os.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchcluster-editor-role
rules:
- apiGroups:
  - opensearch.opster.io
  resources:
  - opensearchcluster
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.opster.io
  resources:
  - opensearchcluster/status
  verbs:
  - get
