# permissions for end users to view opensearchusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchuser-viewer-role
rules:
- apiGroups:
  - opensearch.org
  resources:
  - opensearchusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.org
  resources:
  - opensearchusers/status
  verbs:
  - get
