apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: webhook-service
  namespace: system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
