---
parent: devops
serviceName: opensearch-k8s-operator
unitTests:
  command: cd opensearch-operator && make test
  platform: "linux/amd64,linux/arm64"
build:
  ecrRegistries: plivo-devops
lint:
  command: cd opensearch-operator && make lint
