---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensearch-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: {{ .Values.manager.metricsBindAddress | quote }}
    webhook:
      port: {{ .Values.webhook.port }}
    leaderElection:
      leaderElect: true
      resourceName: a867c7dc.opensearch.opensearch.org
