---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "opensearch-operator.labels" . | nindent 4 }}
  name: {{ include "opensearch-operator.fullname" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "opensearch-operator.selectorLabels" . | nindent 4 }}
