apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: deploy-and-upgrade
  namespace: default
spec:
  bootstrap:
    affinity: {}
    resources: {}
  confMgmt: {}
  dashboards:
    affinity: {}
    enable: true
    opensearchCredentialsSecret:
      name: ""
    podSecurityContext: {}
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
    securityContext: {}
    service:
      type: ClusterIP
    tls:
      caSecret:
        name: ""
      duration: 8760h0m0s
      generate: true
      secret:
        name: ""
    version: 2.19.4
  general:
    drainDataNodes: true
    httpPort: 9200
    monitoring:
      scrapeInterval: 30s
      tlsConfig: {}
    podSecurityContext: {}
    securityContext: {}
    serviceName: opensearch-cluster
    setVMMaxMapCount: true
    vendor: Opensearch
    version: 2.19.4
    additionalConfig:
      cluster.routing.allocation.disk.watermark.low: 500m
      cluster.routing.allocation.disk.watermark.high: 300m
      cluster.routing.allocation.disk.watermark.flood_stage: 100m
  initHelper:
    image: docker.io/busybox:1.36
    imagePullPolicy: IfNotPresent
    resources: {}
    version: "1.36"
  nodePools:
  - component: masters
    diskSize: 30Gi
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    roles:
    - master
    - data
  security:
    config:
      adminCredentialsSecret:
        name: ""
      adminSecret:
        name: ""
      securityConfigSecret:
        name: ""
      updateJob:
        resources: {}
    tls:
      http:
        caSecret:
          name: ""
        duration: 8760h0m0s
        generate: true
        rotateDaysBeforeExpiry: -1
        secret:
          name: ""
      transport:
        caSecret:
          name: ""
        duration: 8760h0m0s
        generate: true
        perNode: true
        rotateDaysBeforeExpiry: -1
        secret:
          name: ""
