apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: deploy-and-upgrade
  namespace: default
spec:
  general:
    version: 1.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: deploy-and-upgrade
    additionalConfig: 
      cluster.routing.allocation.disk.watermark.low: 500m
      cluster.routing.allocation.disk.watermark.high: 300m
      cluster.routing.allocation.disk.watermark.flood_stage: 100m
  confMgmt:
    smartScaler: true
  dashboards:
    version: 1.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "master"
        - "data"
