{{- $labels := include "opensearch-cluster.labels" . }}
{{- $clusterName := include "opensearch-cluster.cluster-name" . }}
{{- range .Values.indexTemplates }}
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: {{ .name }}
  {{- with $.Values.cluster.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  labels: {{ $labels | nindent 4 }}
spec:
  opensearchCluster:
    name: {{ $clusterName }}
  {{- if not (eq .dataStream nil) }}
  dataStream: {{ .dataStream | toYaml | nindent 4 }}
  {{- end }}
  {{- with .indexPatterns }}
  indexPatterns: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .composedOf }}
  composedOf: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .priority }}
  priority: {{ . }}
  {{- end }}
  {{- with .templateSpec }}
  template: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .version }}
  version: {{ . }}
  {{- end }}
  {{- with ._meta }}
  _meta: {{ . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
