# A special manual workflow to push a busybox image into our public ecr registry. This image is used for the init helper containers
name: Push busybox image to ecr
on: workflow_dispatch


jobs:
  release:
    name: Push busybox image to ecr
    runs-on: ubuntu-latest
    environment:
      name: k8s-operator
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull and Push docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd opensearch-operator
          export IMG=public.ecr.aws/opsterio/busybox:1.27.2-buildx
          echo $IMG
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/opsterio
          docker buildx build -f Dockerfile-busybox --platform="linux/amd64,linux/arm,linux/arm64" . -t $IMG --push
          cd ..
